"use strict";
// Real v1 -> v2 migration and browser review, exclusively in fictional /tmp sessions.
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const {spawn, spawnSync} = require("node:child_process");
const {chromium} = require("playwright");
const {expect} = require("@playwright/test");
const ROOT = path.resolve(__dirname,"../..");
const temp = fs.mkdtempSync(path.join(os.tmpdir(),"evidence-policy-browser-"));
const bundleDir=path.join(temp,"bundle");fs.mkdirSync(bundleDir);
const bundleFile = path.join(bundleDir,"fixture.json"), policyFile = path.join(temp,"policy.json"), sessionFile = path.join(temp,"human-session.json");
const screenshots = path.join(temp,"screenshots");fs.mkdirSync(screenshots);
const reviewer = "automated-policy-browser-test";
const sha = value=>crypto.createHash("sha256").update(value).digest("hex");
const parentPolicy = {version:"fictional-policy-v1",sha256:"f".repeat(64)};
const values = {hate:"non-hate",group:null,hate_reason:"opposes_attack",group_reason:"category_boundary",stance:"opposes",target_types:["group"],expression_types:["quoted_rebuttal"],evidence:[],note:"虚构旧规则审核，group 范围尚未解决。"};
const object = (id,kind,source,draft,depends_on=[])=>({id,kind,source,depends_on,version:"fictional-source-v1",ai_draft:{review_kind:"ai_note",version:"fictional-ai-v1",values:draft,provenance:{model:"automated-fixture",input_scope:"fictional materials only"}}});
const objects = {
  q1:object("q1","query",{text:"异性恋不该因一个人的行为被全体污名化。"},values),
  q2:object("q2","query",{text:"我的异性恋同事今天迟到了。"},{...values,group:[],group_reason:"no_group_target",hate_reason:"behavior_criticism",stance:"neutral",target_types:["individual"],expression_types:["behavior_criticism"]}),
  demo:object("demo","demo",{text:"不该因为一名游客插队就贬低所有游客。",demo_id:"fictional-demo",original_answer:{hate:"non-hate",group:[]}},{...values,hate_original_status:"accepted",group_original_status:"policy_ambiguous"}),
  definition:object("definition","definition",{text:"游客指旅行游览的人。",term:"游客"},{definition_verdict:"reasonable",issues:["valid_sense"],evidence:[],note:""}),
};
const cases={};
for(const i of [1,2]){
  objects["r"+i]=object("r"+i,"relation",{texts:{query:objects["q"+i].source.text,demo:objects.demo.source.text}},{topic_hate:"partial",topic_group:"unclear",rule_hate:"direct",rule_group:"unclear",lexicon_risk:"no",evidence:[],note:"虚构旧关联。"},["q"+i,"demo"]);
  objects["h"+i]=object("h"+i,"hit",{texts:{query:objects["q"+i].source.text,definition:objects.definition.source.text},term:"游客"},{source_fit:"valid_sense",query_fit:"inapplicable",issues:["valid_sense"],evidence:[],note:""},["q"+i,"definition"]);
  cases["c"+i]={split:"discovery",query_object_id:"q"+i,object_ids:["q"+i,"demo","definition","r"+i,"h"+i],comparison:{gold:{hate:"non-hate",group:[]},trajectories:{"0":{hate:{prediction:"non-hate"},group:{prediction:[]}}},ai_proposal:{candidate_explanation:"虚构旧版解释提案。"}}};
}
fs.writeFileSync(bundleFile,JSON.stringify({schema_version:"general-model-evidence-bundle/v1",policy:parentPolicy,source_identity:"fictional-policy-browser-fixture",order:["c1","c2"],cases,objects}));
// Exercise the actual approved long document's rendering, without any real cases or records.
const publishedPolicy=JSON.parse(fs.readFileSync(path.join(ROOT,"exps/causal_context/general_model_evidence_applicability_v1/policies/group-scope-v2/policy_amendment.json"),"utf8"));
const activePolicy={schema_version:"general-model-evidence-policy-amendment/v1",version:"fictional-policy-v2",title:"虚构审核 · group 对象范围 v2",document_text:publishedPolicy.document_text,sha256:sha(publishedPolicy.document_text),parent_policy:parentPolicy,bundle_sha256:sha(fs.readFileSync(bundleFile)),approval:{reviewer_id:reviewer,confirmed_at:"2026-09-09T00:00:00Z",statement:"isolated automated fixture"},impact:{tasks:["group"],object_ids:["q1","q2","demo","r1","r2"],case_ids:["c1","c2"]}};
fs.writeFileSync(policyFile,JSON.stringify(activePolicy));
let service,browser,baseUrl,serviceLog="",activeSession=sessionFile;const errors=[];
async function startService(v2=false){
  serviceLog="";const args=["scripts/stage1/general_model_paired_review.py","--session-file",path.join(temp,"old-isolated.json"),"--reviewer-id",reviewer,"--port",baseUrl?new URL(baseUrl).port:"0","--evidence-bundle",bundleFile,"--evidence-session",activeSession];if(v2)args.push("--evidence-policy",policyFile);
  service=spawn(process.env.PAIRED_REVIEW_PYTHON||"/usr/bin/python3",args,{cwd:ROOT,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"},stdio:["ignore","pipe","pipe"]});service.stderr.on("data",data=>serviceLog+=data.toString());
  return new Promise((resolve,reject)=>{let stdout="";const timeout=setTimeout(()=>reject(new Error("Server startup timeout: "+serviceLog)),10000);service.once("exit",code=>{clearTimeout(timeout);reject(new Error("Server exited "+code+": "+serviceLog));});service.stdout.on("data",data=>{stdout+=data.toString();try{const info=JSON.parse(stdout.split("\n")[0]);if(info.url){clearTimeout(timeout);resolve(info.url);}}catch(_){}});});
}
async function stopService(){if(service&&service.exitCode===null)await new Promise(resolve=>{service.once("exit",resolve);service.kill("SIGTERM");});service=null;}
const boot=async page=>(await(await page.request.get(baseUrl+"api/evidence/bootstrap")).json());
const item=async(page,key="c1")=>(await(await page.request.get(baseUrl+"api/evidence/items/"+key)).json());
async function post(page,action,payload){const b=await boot(page);const response=await page.request.post(baseUrl+"api/evidence/"+action,{data:{session_token:b.session_token,expected_revision:b.revision,...payload}});assert.ok(response.ok(),action+": "+await response.text());return response.json();}
async function seedV1(page){
  for(const id of cases.c1.object_ids){const current=await item(page);const o=current.objects.find(row=>row.id===id);await post(page,"confirm-object",{item_id:"c1",object_id:id,object_version:o.review.version,values:o.effective_values,prior_exposure:current.review.prior_exposure});}
  await post(page,"reveal",{item_id:"c1"});
  await post(page,"confirm",{item_id:"c1",assessment:{hate:"non-hate",group:null,hate_original_status:"accepted",group_original_status:"policy_ambiguous",hate_use:"reference_analysis",group_use:"verify_first",explanation_choice:"adopt",note:"虚构旧版最终裁决。"},prior_exposure:(await item(page)).review.prior_exposure});
}
async function choose(page,field,value){await page.locator(`[data-field="${field}"] [data-value="${value}"]`).click();}
async function save(page){await page.locator("#save-draft").click();await expect(page.locator("#save-state")).toHaveAttribute("data-state","saved");}
async function checkLayouts(){
  for(const viewport of [{width:1440,height:1000},{width:1024,height:768},{width:390,height:844},{width:844,height:390}]){
    const context=await browser.newContext({viewport});const page=await context.newPage();page.on("pageerror",error=>errors.push(String(error)));await page.goto(baseUrl+"evidence/");await expect(page.locator("#item-id")).toHaveText("案例 #c1");
    const revision=(await boot(page)).revision;await expect(page.locator("#policy-version")).toHaveText(activePolicy.version);await expect(page.locator("#policy-origin")).toContainText("没有按 group v2 重写");await page.locator("#policy-details summary").click();await expect(page.locator("#policy-document")).toContainText("异性恋这一性取向属性");await expect(page.locator("#policy-document h3").last()).toHaveText("11. 冻结回执");
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"Expanded long policy must not cause page overflow");assert.ok(await page.locator("#policy-document").evaluate(e=>e.scrollWidth<=e.clientWidth+1),"Policy tables must fit the column");
    await page.screenshot({path:path.join(screenshots,"policy-"+viewport.width+"x"+viewport.height+".png")});await page.locator("#policy-details summary").click();await expect(page.locator("#policy-details")).not.toHaveAttribute("open","");
    await page.locator("#guidelines").click();await expect(page.locator("#guideline-policy-note")).toContainText("规则变化（已裁决）");await expect(page.locator("#dismiss-guidelines")).toBeInViewport();await expect(page.locator("#close-guidelines")).toBeInViewport();await page.keyboard.press("Escape");await expect(page.locator("#guidelines")).toBeFocused();assert.equal((await boot(page)).revision,revision,"Reading and dismissing policies must not save records");await context.close();
  }
  console.log("PASS active policy and complete rules at desktop/tablet/mobile/landscape; safe expansion, dismiss/focus, no record writes");
}
async function main(){
  baseUrl=await startService();browser=await chromium.launch({headless:true});const seedContext=await browser.newContext();const seedPage=await seedContext.newPage();await seedV1(seedPage);const before=await item(seedPage);assert.equal(before.review.status,"confirmed");const originalBytes=fs.readFileSync(sessionFile);
  await seedPage.goto(baseUrl+"evidence/");await seedPage.locator('[data-item-id="c1"]').click();await expect(seedPage.locator("#item-id")).toHaveText("案例 #c1");const oldBoot=await boot(seedPage);const localDraft={item_id:"c1",object_id:"q1",mode:"materials",revision:oldBoot.revision,object_version:before.objects.find(o=>o.id==="q1").review.version,values:{...before.objects.find(o=>o.id==="q1").effective_values,hate:"hate",hate_reason:"agreed_attack",note:"v1 未保存的 hate 与共同依据草稿。"},prior_exposure:before.review.prior_exposure};const backupKey=["evidence-human-review",oldBoot.bundle_sha256,reviewer,"c1"].join(":");await seedPage.evaluate(({key,value})=>localStorage.setItem(key,JSON.stringify(value)),{key:backupKey,value:localDraft});
  await stopService();
  const prior=JSON.parse(originalBytes);const migration=spawnSync(process.env.PAIRED_REVIEW_PYTHON||"/usr/bin/python3",["-m","tools.general_model_paired_review_ui.evidence_policy","--bundle",bundleFile,"--policy",policyFile,"--session",sessionFile,"--reviewer-id",reviewer,"--expected-revision",prior.revision,"--expected-session-sha256",sha(originalBytes),"--actor","isolated-browser-test"],{cwd:ROOT,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1",PYTHONPATH:path.join(ROOT,"src")},encoding:"utf8"});assert.equal(migration.status,0,migration.stderr);const receipt=JSON.parse(migration.stdout);assert.equal(receipt.human_confirmations_added,0);assert.deepEqual(fs.readFileSync(receipt.backup_path),originalBytes);const migratedBytes=fs.readFileSync(sessionFile);
  baseUrl=await startService(true);await checkLayouts();
  const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on("pageerror",error=>errors.push(String(error)));await page.goto(baseUrl+"evidence/");await expect(page.locator("#object-select")).toHaveValue("q1");const migrated=await item(page);
  assert.equal(migrated.review.status,"confirmed");assert.equal(migrated.needs_group_recheck,true);assert.deepEqual(migrated.review.material_snapshots,before.review.material_snapshots);assert.deepEqual(migrated.review.assessment,before.review.assessment);assert.ok(migrated.comparison,"Previously seen results remain visible");
  await expect(page.locator("#case-policy-notice")).toContainText("group 需要按 v2");await expect(page.locator("#group-policy-notice")).toContainText("已确认的 hate");await expect(page.locator('[data-field="hate"] button').first()).toBeDisabled();await expect(page.locator("#review-note")).toBeDisabled();await expect(page.locator('[data-field="group_mode"] [data-value="classes"]')).toBeEnabled();await expect(page.locator("#reopen")).toContainText("同时修改 hate");
  await choose(page,"group_mode","classes");await choose(page,"group","others");await choose(page,"group_reason","group_evaluation");await save(page);const savedQuery=(await item(page)).objects.find(o=>o.id==="q1");assert.deepEqual(savedQuery.review.values.group,["others"]);assert.equal(savedQuery.needs_group_recheck,true,"A save is not an explicit group confirmation");assert.deepEqual(savedQuery.review.task_reviews.hate,migrated.objects.find(o=>o.id==="q1").review.task_reviews.hate);
  await page.locator("#object-select").selectOption("demo");await expect(page.locator('[data-field="hate_original_status"] [data-value="policy_changed"]')).toHaveCount(0);await expect(page.locator('[data-field="group_original_status"] [data-value="policy_changed"]')).toBeEnabled();await choose(page,"group_mode","classes");await choose(page,"group","others");await choose(page,"group_reason","group_evaluation");await choose(page,"group_original_status","policy_changed");await save(page);
  await page.locator("#open-batch").click();await expect(page.locator("#batch-items input:checked")).toHaveCount(0);await expect(page.locator("#batch-items")).toContainText("本项仅确认 group 已按 v2 重核");await page.locator('#batch-items input[value="q1"]').check();await page.locator('#batch-items input[value="demo"]').check();await page.locator("#confirm-batch").click();await expect(page.locator("#batch-dialog")).not.toBeVisible();
  for(const id of ["q1","demo"]){const row=(await item(page)).objects.find(o=>o.id===id);assert.equal(row.needs_group_recheck,false);assert.deepEqual(row.review.task_reviews.hate,migrated.objects.find(o=>o.id===id).review.task_reviews.hate);assert.deepEqual(row.ai_draft.values,objects[id].ai_draft.values);}
  for(const id of ["definition","h1"]){const row=(await item(page)).objects.find(o=>o.id===id);assert.equal(row.stale,false,"Group-only changes must not invalidate "+id);assert.deepEqual(row.review,migrated.objects.find(o=>o.id===id).review);}
  await page.locator("#object-select").selectOption("r1");await expect(page.locator('[data-field="rule_hate"] button').first()).toBeDisabled();await choose(page,"topic_group","partial");await choose(page,"rule_group","direct");await page.locator("#primary-action").click();await expect(page.locator("#save-state")).toHaveAttribute("data-state","saved");await expect(page.locator("#reveal-comparison")).toBeEnabled();await page.locator("#reveal-comparison").click();await expect(page.locator("#panel-comparison")).toBeVisible();await expect(page.locator("#panel-comparison")).toContainText("未按 group v2 重新生成");await expect(page.getByRole("group",{name:"查询原标注",exact:true}).getByRole("button",{name:"未见过",exact:true})).toBeDisabled();
  await expect(page.locator('[data-field="hate_original_status"] button').first()).toBeDisabled();await expect(page.locator('[data-field="hate_use"] button').first()).toBeDisabled();await expect(page.locator('[data-field="group_use"] [data-value="reference_analysis"]')).toBeEnabled();await choose(page,"group_mode","classes");await choose(page,"group","others");await page.locator("#check-reasons").click();await choose(page,"group_original_status","policy_changed");await choose(page,"group_use","reference_analysis");await page.locator("#primary-action").click();await expect(page.locator("#item-id")).toHaveText("案例 #c2");
  const final=await item(page);assert.equal(final.needs_group_recheck,false);assert.deepEqual(final.review.task_reviews.hate,migrated.review.task_reviews.hate);assert.deepEqual(final.review.assessment.group,["others"]);assert.equal(final.review.assessment.group_original_status,"policy_changed");assert.equal(final.review.assessment.hate,before.review.assessment.hate);assert.equal(final.review.assessment.note,before.review.assessment.note);assert.ok(final.review.material_snapshots.length>before.review.material_snapshots.length);assert.deepEqual(final.review.material_snapshots[0],before.review.material_snapshots[0]);
  await expect(page.locator("#group-policy-notice")).toContainText("AI 初稿或旧草稿不算人工确认");await expect(page.locator('[data-field="hate"] button').first()).toBeEnabled();assert.equal((await item(page,"c2")).objects.find(o=>o.id==="q2").review.status,"unreviewed");
  console.log("PASS actual v1 migration preserves hate, history, AI drafts and previously seen results; group-only fields/save/batch/relation/final require explicit recheck; fresh AI stays unreviewed");
  // Full amendment remains available when a group recheck needs changed shared evidence.
  await page.locator("#object-select").selectOption("demo");await page.locator("#reopen").click();await page.locator("#reopen-reason").selectOption("new_evidence");await page.locator("#confirm-reopen").click();await expect(page.locator("#reopen-dialog")).not.toBeVisible();await expect(page.locator("#review-note")).toBeEnabled();await expect(page.locator('[data-field="hate"] button').first()).toBeEnabled();await page.locator("#review-note").fill("虚构新证据：显式重新打开后才编辑共同字段。");await save(page);assert.equal((await item(page,"c2")).objects.find(o=>o.id==="demo").review.values.note,"虚构新证据：显式重新打开后才编辑共同字段。");
  await page.screenshot({path:path.join(screenshots,"group-review-desktop.png")});await context.close();await stopService();baseUrl=await startService(true);const resumedContext=await browser.newContext();const resumed=await resumedContext.newPage();await resumed.goto(baseUrl+"evidence/");await expect(resumed.locator("#policy-version")).toHaveText(activePolicy.version);const restarted=await item(resumed);assert.equal(restarted.review.assessment.group_original_status,"policy_changed");assert.deepEqual(restarted.review.task_reviews.hate,final.review.task_reviews.hate);await resumedContext.close();
  await stopService();activeSession=path.join(temp,"recovery-session.json");fs.writeFileSync(activeSession,migratedBytes);baseUrl=await startService(true);
  // The same origin/key survives a policy upgrade; a conflicting old draft needs explicit amendment.
  await seedPage.reload();await expect(seedPage.locator("#recover-local")).toBeVisible();assert.deepEqual(await seedPage.evaluate(key=>JSON.parse(localStorage.getItem(key)),backupKey),localDraft);await seedPage.locator("#recover-local").click();await expect(seedPage.locator("#request-error-message")).toContainText("本地草稿包含本次 group 重核之外的修改");await expect(seedPage.locator('[data-field="hate"] button').first()).toBeDisabled();assert.deepEqual(await seedPage.evaluate(key=>JSON.parse(localStorage.getItem(key)),backupKey),localDraft);assert.equal((await item(seedPage)).objects.find(o=>o.id==="q1").review.values.hate,"non-hate");
  await seedPage.locator("#reopen").click();await seedPage.locator("#reopen-reason").selectOption("new_evidence");await seedPage.locator("#confirm-reopen").click();await expect(seedPage.locator("#reopen-dialog")).not.toBeVisible();await seedPage.locator("#recover-local").click();await expect(seedPage.locator("#review-note")).toHaveValue(localDraft.values.note);await expect(seedPage.locator('[data-field="hate"] [data-value="hate"]')).toHaveAttribute("aria-pressed","true");await seedPage.waitForTimeout(5200);assert.equal((await item(seedPage)).objects.find(o=>o.id==="q1").review.values.hate,"non-hate","Recovery must not autosave an old-policy draft");await save(seedPage);assert.equal((await item(seedPage)).objects.find(o=>o.id==="q1").review.values.hate,"hate");assert.equal((await item(seedPage)).objects.find(o=>o.id==="q1").review.values.note,localDraft.values.note);await seedContext.close();
  assert.deepEqual(errors,[]);console.log("PASS explicit amendment, restart persistence and cross-policy local-draft recovery without silent hate overwrite; screenshots: "+screenshots);
}
main().catch(error=>{console.error(error);console.error(serviceLog);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await stopService();});
