"use strict";
// Material navigation uses fictional materials and temporary review sessions only.
const assert=require("node:assert/strict");
const fs=require("node:fs"),os=require("node:os"),path=require("node:path"),crypto=require("node:crypto");
const {spawn,spawnSync}=require("node:child_process");
const {chromium}=require("playwright");const {expect}=require("@playwright/test");
const ROOT=path.resolve(__dirname,"../..");
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"evidence-navigation-browser-"));
const bundleDir=path.join(temp,"bundle"),screenshots=path.join(temp,"screenshots");fs.mkdirSync(bundleDir);fs.mkdirSync(screenshots);
const bundleFile=path.join(bundleDir,"fixture.json"),sessionFile=path.join(temp,"human.json"),policyFile=path.join(temp,"policy.json");
const reviewer="automated-navigation-browser-test",sha=value=>crypto.createHash("sha256").update(value).digest("hex");
const labels={hate:"non-hate",group:[],hate_reason:"no_attack",group_reason:"no_group_target",stance:"neutral",target_types:["none"],expression_types:["neutral_or_laughter"],evidence:[],note:""};
const make=(id,kind,source,values,depends_on=[])=>({id,kind,source,depends_on,version:"fictional-source-v1",ai_draft:{review_kind:"ai_note",version:"fictional-ai-v1",values,provenance:{model:"automated-fixture",input_scope:"fictional materials only"}}});
const objects={
  q1:make("q1","query",{text:"异性恋不该因个人行为被全体污名化。"},{...labels,group:null,group_reason:"category_boundary"}),
  d1:make("d1","demo",{text:"虚构示例一：今天适合散步。",demo_id:"fictional-one",original_answer:{hate:"non-hate",group:[]}},{...labels,hate_original_status:"accepted",group_original_status:"accepted"}),
  definition:make("definition","definition",{text:"散步指缓慢步行。",term:"散步"},{definition_verdict:"reasonable",issues:["valid_sense"],evidence:[],note:""}),
  d2:make("d2","demo",{text:"虚构示例二：明天去公园。",demo_id:"fictional-two",original_answer:{hate:"non-hate",group:[]}},{...labels,hate_original_status:"accepted",group_original_status:"accepted"}),
  q2:make("q2","query",{text:"虚构案例二只有一项查询材料。"},labels),
};
objects.r1=make("r1","relation",{texts:{query:objects.q1.source.text,demo:objects.d1.source.text}},{topic_hate:"none",topic_group:"none",rule_hate:"none",rule_group:"none",lexicon_risk:"no",evidence:[],note:""},["q1","d1"]);
objects.h1=make("h1","hit",{texts:{query:objects.q1.source.text,definition:objects.definition.source.text},term:"散步"},{source_fit:"valid_sense",query_fit:"inapplicable",issues:["valid_sense"],evidence:[],note:""},["q1","definition"]);
const comparison={gold:{hate:"non-hate",group:[]},trajectories:{"0":{hate:{prediction:"non-hate"},group:{prediction:[]}}},ai_proposal:{candidate_explanation:"虚构测试解释。"}};
const cases={c1:{split:"discovery",query_object_id:"q1",object_ids:["q1","d1","definition","d2","r1","h1"],comparison},c2:{split:"discovery",query_object_id:"q2",object_ids:["q2"],comparison}};
const parentPolicy={version:"fixture-v1",sha256:"f".repeat(64)};
fs.writeFileSync(bundleFile,JSON.stringify({schema_version:"general-model-evidence-bundle/v1",policy:parentPolicy,source_identity:"fictional-navigation-fixture",order:["c1","c2"],objects,cases}));
const policyText="# 虚构导航测试规则 v2\n\n仅用于隔离浏览器测试。\n\n## group\n\n异性恋群体评价归 others；hate 独立。\n";
fs.writeFileSync(policyFile,JSON.stringify({schema_version:"general-model-evidence-policy-amendment/v1",version:"fixture-v2",title:"虚构 group v2",document_text:policyText,sha256:sha(policyText),parent_policy:parentPolicy,bundle_sha256:sha(fs.readFileSync(bundleFile)),approval:{reviewer_id:reviewer,confirmed_at:"2026-09-09T00:00:00Z"},impact:{tasks:["group"],object_ids:["q1","q2","d1","d2","r1"],case_ids:["c1","c2"]}}));
let service,browser,baseUrl,serviceLog="";const errors=[];
async function startService(v2=false){
  serviceLog="";const args=["scripts/stage1/general_model_paired_review.py","--session-file",path.join(temp,"old-isolated.json"),"--reviewer-id",reviewer,"--port","0","--evidence-bundle",bundleFile,"--evidence-session",sessionFile];if(v2)args.push("--evidence-policy",policyFile);
  service=spawn(process.env.PAIRED_REVIEW_PYTHON||"/usr/bin/python3",args,{cwd:ROOT,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1"},stdio:["ignore","pipe","pipe"]});service.stderr.on("data",data=>serviceLog+=data);
  return new Promise((resolve,reject)=>{let stdout="";const timeout=setTimeout(()=>reject(new Error("Server timeout: "+serviceLog)),10000);service.once("exit",code=>{clearTimeout(timeout);reject(new Error("Server exited "+code+": "+serviceLog));});service.stdout.on("data",data=>{stdout+=data;try{const info=JSON.parse(stdout.split("\n")[0]);if(info.url){clearTimeout(timeout);resolve(info.url);}}catch(_){}});});
}
async function stopService(){if(service&&service.exitCode===null)await new Promise(resolve=>{service.once("exit",resolve);service.kill("SIGTERM");});service=null;}
const boot=async page=>(await(await page.request.get(baseUrl+"api/evidence/bootstrap")).json());
const item=async(page,id="c1")=>(await(await page.request.get(baseUrl+"api/evidence/items/"+id)).json());
const select=async(page,id)=>{await page.locator("#object-select").selectOption(id);await expect(page.locator("#object-select")).toHaveValue(id);};
const bodyFocus=async page=>page.evaluate(()=>document.activeElement?.blur());
const choose=async(page,field,value)=>page.locator(`[data-field="${field}"] [data-value="${value}"]`).click();
async function save(page){await page.locator("#save-draft").click();await expect(page.locator("#save-state")).toHaveAttribute("data-state","saved");}
async function assertObject(page,id){await expect(page.locator("#object-select")).toHaveValue(id);await expect(page.locator("#item-id")).toHaveText("案例 #c1");}
async function readOnlyLayouts(){
  for(const viewport of [{width:1440,height:1000},{width:1024,height:768},{width:390,height:844},{width:320,height:740}]){
    const context=await browser.newContext({viewport});const page=await context.newPage();page.on("pageerror",error=>errors.push(String(error)));const posts=[];page.on("request",request=>{if(request.method()==="POST")posts.push(request.url());});await page.goto(baseUrl+"evidence/");await assertObject(page,"q1");const revision=(await boot(page)).revision;
    await page.locator(".object-navigation").scrollIntoViewIfNeeded();await expect(page.locator("#previous-object")).toBeDisabled();await expect(page.locator("#next-object")).toBeEnabled();await expect(page.locator("#object-position")).toHaveText("1 / 6");
    await page.locator("#next-object").click();await assertObject(page,"d1");await page.locator("#previous-object").click();await assertObject(page,"q1");await bodyFocus(page);await page.keyboard.press("Alt+ArrowDown");await assertObject(page,"d1");await page.keyboard.press("Alt+ArrowUp");await assertObject(page,"q1");
    await page.locator('[data-kind="demo"]').click();await assertObject(page,"d1");await expect(page.locator("#object-position")).toHaveText("1 / 2");await page.locator("#next-object").click();await assertObject(page,"d2");await expect(page.locator("#next-object")).toBeDisabled();await bodyFocus(page);await page.keyboard.press("Alt+ArrowDown");await assertObject(page,"d2");await page.keyboard.press("Alt+ArrowUp");await assertObject(page,"d1");
    await page.locator('[data-kind="lexicon"]').click();await assertObject(page,"definition");await page.locator("#next-object").click();await assertObject(page,"h1");await expect(page.locator("#next-object")).toBeDisabled();await page.locator('[data-kind="query"]').click();await assertObject(page,"q1");await expect(page.locator("#previous-object")).toBeDisabled();await expect(page.locator("#next-object")).toBeDisabled();
    await page.locator('[data-kind="all"]').click();await page.locator(".object-navigation").scrollIntoViewIfNeeded();
    const geometry=await page.locator(".object-navigation").evaluate(element=>({overflow:element.scrollWidth-element.clientWidth,buttons:[...element.querySelectorAll("button")].map(button=>{const box=button.getBoundingClientRect();const hit=document.elementFromPoint(box.x+box.width/2,box.y+box.height/2);return{width:box.width,height:box.height,visible:box.left>=0&&box.right<=innerWidth&&box.top>=0&&box.bottom<=innerHeight,hit:hit===button||button.contains(hit)};})}));assert.ok(geometry.overflow<=1);for(const button of geometry.buttons){assert.ok(button.width>80&&button.height>=(viewport.width<=760?44:40));assert.ok(button.visible&&button.hit);}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(screenshots,`material-navigation-${viewport.width}.png`)});assert.equal((await boot(page)).revision,revision);assert.deepEqual(posts,[]);await context.close();
  }
  console.log("PASS buttons and Alt arrows, filtered order, single/last boundaries without crossing cases, 1440/1024/390/320 layouts, zero POST for navigation");
}
async function main(){
  baseUrl=await startService();browser=await chromium.launch({headless:true});const seedContext=await browser.newContext(),seed=await seedContext.newPage();const b=await boot(seed);const seeded=await seed.request.post(baseUrl+"api/evidence/confirm-object",{data:{session_token:b.session_token,expected_revision:b.revision,item_id:"c1",object_id:"q1",object_version:0,values:objects.q1.ai_draft.values}});assert.ok(seeded.ok(),await seeded.text());await seedContext.close();await stopService();
  const prior=JSON.parse(fs.readFileSync(sessionFile,"utf8"));const migration=spawnSync(process.env.PAIRED_REVIEW_PYTHON||"/usr/bin/python3",["-m","tools.general_model_paired_review_ui.evidence_policy","--bundle",bundleFile,"--policy",policyFile,"--session",sessionFile,"--reviewer-id",reviewer,"--expected-revision",prior.revision,"--actor","isolated-navigation-test"],{cwd:ROOT,env:{...process.env,PYTHONDONTWRITEBYTECODE:"1",PYTHONPATH:path.join(ROOT,"src")},encoding:"utf8"});assert.equal(migration.status,0,migration.stderr);baseUrl=await startService(true);await readOnlyLayouts();
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on("pageerror",error=>errors.push(String(error)));const saveRequests=[];page.on("request",request=>{if(request.url().endsWith("/save-object"))saveRequests.push(request.postDataJSON());});await page.goto(baseUrl+"evidence/");await assertObject(page,"q1");await expect(page.locator("#previous-object")).toHaveAttribute("aria-keyshortcuts","Alt+ArrowUp");await expect(page.locator("#next-object")).toHaveAttribute("aria-keyshortcuts","Alt+ArrowDown");
  await select(page,"d1");
  for(const target of ["#item-search","#object-select","#review-note"]){await page.locator(target).focus();const intercepted=await page.locator(target).evaluate(element=>{const event=new KeyboardEvent("keydown",{key:"ArrowDown",altKey:true,bubbles:true,cancelable:true});element.dispatchEvent(event);return event.defaultPrevented;});assert.equal(intercepted,false,target+" must retain its native key handling");await assertObject(page,"d1");}
  await page.evaluate(()=>{const editor=document.createElement("div");editor.id="test-editable";editor.contentEditable="true";document.body.append(editor);editor.focus();});assert.equal(await page.locator("#test-editable").evaluate(element=>{const event=new KeyboardEvent("keydown",{key:"ArrowDown",altKey:true,bubbles:true,cancelable:true});element.dispatchEvent(event);return event.defaultPrevented;}),false);await page.locator("#test-editable").evaluate(element=>element.remove());
  for(const extra of [{isComposing:true},{keyCode:229},{repeat:true},{ctrlKey:true},{metaKey:true},{shiftKey:true}]){assert.equal(await page.evaluate(extra=>{const event=new KeyboardEvent("keydown",{key:"ArrowDown",altKey:true,bubbles:true,cancelable:true,...extra});document.body.dispatchEvent(event);return event.defaultPrevented;},extra),false);await assertObject(page,"d1");}
  await page.locator("#guidelines").click();await page.keyboard.press("Alt+ArrowDown");await assertObject(page,"d1");await page.keyboard.press("Escape");await expect(page.locator("#guideline-dialog")).not.toBeVisible();console.log("PASS accessible shortcut labels; input/select/contenteditable, IME, repeat, extra modifiers and dialogs do not trigger material navigation");
  await select(page,"q1");const previousHate=(await item(page)).objects.find(o=>o.id==="q1").review.task_reviews.hate;await expect(page.locator('[data-field="hate"] button').first()).toBeDisabled();await choose(page,"group_mode","classes");await choose(page,"group","others");await choose(page,"group_reason","group_evaluation");await page.locator("#next-object").click();await assertObject(page,"d1");const savedQuery=(await item(page)).objects.find(o=>o.id==="q1");assert.deepEqual(savedQuery.review.values.group,["others"]);assert.equal(savedQuery.needs_group_recheck,true);assert.deepEqual(savedQuery.review.task_reviews.hate,previousHate);
  await page.locator("#review-note").fill("离开示例前保存的草稿。");await page.locator("#next-object").click();await assertObject(page,"definition");assert.equal((await item(page)).objects.find(o=>o.id==="d1").review.values.note,"离开示例前保存的草稿。");await page.locator("#previous-object").click();await assertObject(page,"d1");await expect(page.locator("#review-note")).toHaveValue("离开示例前保存的草稿。");
  const beforeFailure=(await boot(page)).revision;await page.locator("#review-note").fill("请求失败也必须留在这项。");await page.route("**/api/evidence/save-object",route=>route.abort("failed"));
  for(const action of ["button","keyboard","filter","select"]){const count=saveRequests.length;if(action==="button")await page.locator("#next-object").click();if(action==="keyboard"){await bodyFocus(page);await page.keyboard.press("Alt+ArrowDown");}if(action==="filter")await page.locator('[data-kind="demo"]').click();if(action==="select")await page.locator("#object-select").selectOption("d2");await expect.poll(()=>saveRequests.length).toBe(count+1);await expect(page.locator("#save-state")).toHaveAttribute("data-state","error");await assertObject(page,"d1");await expect(page.locator('[data-kind="all"]')).toHaveClass(/active/);await expect(page.locator("#review-note")).toHaveValue("请求失败也必须留在这项。");assert.equal((await boot(page)).revision,beforeFailure);}
  await page.unroute("**/api/evidence/save-object");await page.locator("#next-object").click();await assertObject(page,"definition");await page.locator("#previous-object").click();await assertObject(page,"d1");
  await choose(page,"group_mode","unknown");await choose(page,"group_mode","classes");const beforeInvalid=saveRequests.length;await page.locator("#next-object").click();await expect(page.locator("#request-error-message")).toContainText("请选择至少一个类别");await page.locator('[data-kind="lexicon"]').click();await page.locator("#object-select").selectOption("d2");await assertObject(page,"d1");await expect(page.locator('[data-kind="all"]')).toHaveClass(/active/);assert.equal(saveRequests.length,beforeInvalid);await choose(page,"group_mode","empty");await page.locator("#check-reasons").click();await save(page);console.log("PASS save-before-navigation including v2 group-only/hate preservation; failed requests and incomplete groups retain material, filter, draft and revision");
  const otherContext=await browser.newContext({viewport:{width:1440,height:1000}}),other=await otherContext.newPage();await other.goto(baseUrl+"evidence/");await select(other,"d1");await page.locator("#review-note").fill("冲突中的本地草稿。");await other.locator("#review-note").fill("另一页面先保存。");await save(other);await page.locator("#next-object").click();await expect(page.locator("#recover-local")).toBeVisible();await assertObject(page,"d1");await expect(page.locator("#next-object")).toBeDisabled();await bodyFocus(page);await page.keyboard.press("Alt+ArrowDown");await page.locator('[data-kind="demo"]').click();await page.locator("#object-select").selectOption("d2");await assertObject(page,"d1");await expect(page.locator('[data-kind="all"]')).toHaveClass(/active/);await expect(page.locator("#review-note")).toHaveValue("冲突中的本地草稿。");await page.locator("#recover-local").click();await expect(page.locator("#resume-notice")).toBeVisible();await page.locator("#next-object").click();await assertObject(page,"definition");assert.equal((await item(page)).objects.find(o=>o.id==="d1").review.values.note,"冲突中的本地草稿。");await otherContext.close();
  await select(page,"d1");await page.locator("#review-note").fill("连续操作只提交这一项一次。");let releaseSave;const held=[];await page.route("**/api/evidence/save-object",async route=>{held.push(route.request().postDataJSON());await new Promise(resolve=>releaseSave=resolve);await route.continue();});await page.locator("#next-object").click();await expect.poll(()=>Boolean(releaseSave)).toBe(true);await expect(page.locator("#previous-object")).toBeDisabled();await expect(page.locator("#next-object")).toBeDisabled();await expect(page.locator("#object-select")).toBeDisabled();await expect(page.locator('[data-kind="demo"]')).toBeDisabled();
  await page.evaluate(()=>{document.getElementById("next-object").click();document.getElementById("previous-object").click();document.body.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowDown",altKey:true,bubbles:true,cancelable:true}));});assert.equal(held.length,1);assert.equal(held[0].object_id,"d1");releaseSave();await assertObject(page,"definition");await page.unroute("**/api/evidence/save-object");assert.equal((await item(page)).objects.find(o=>o.id==="d1").review.values.note,"连续操作只提交这一项一次。");assert.equal((await item(page)).objects.find(o=>o.id==="definition").review.values,null);
  await select(page,"d1");const beforeRapid=saveRequests.length;await page.evaluate(()=>{document.getElementById("next-object").click();document.getElementById("next-object").click();});await assertObject(page,"definition");assert.equal(saveRequests.length,beforeRapid);console.log("PASS conflicts retain drafts and block all material navigation; delayed/rapid repeated actions cannot duplicate saves or skip/overwrite another material");
  await bodyFocus(page);await page.keyboard.press("]");await expect(page.locator("#item-id")).toHaveText("案例 #c2");await expect(page.locator("#object-select")).toHaveValue("q2");await expect(page.locator("#previous-object")).toBeDisabled();await expect(page.locator("#next-object")).toBeDisabled();await expect(page.locator('[data-kind="demo"]')).toBeDisabled();await expect(page.locator('[data-kind="lexicon"]')).toBeDisabled();await page.keyboard.press("Alt+ArrowUp");await expect(page.locator("#item-id")).toHaveText("案例 #c2");await page.locator("#primary-action").click();await expect(page.locator("#reveal-comparison")).toBeEnabled();await page.locator("#reveal-comparison").click();await expect(page.locator("#panel-comparison")).toBeVisible();await expect(page.locator("#previous-object")).toBeDisabled();await expect(page.locator("#next-object")).toBeDisabled();const beforeComparison=(await boot(page)).revision;await bodyFocus(page);await page.keyboard.press("Alt+ArrowDown");await expect(page.locator("#panel-comparison")).toBeVisible();assert.equal((await boot(page)).revision,beforeComparison);await page.keyboard.press("[");await expect(page.locator("#item-id")).toHaveText("案例 #c1");
  assert.deepEqual(errors,[]);await context.close();console.log("PASS empty-type/single-material controls, comparison mode disabled, existing [ ] case shortcuts; screenshots: "+screenshots);
}
main().catch(error=>{console.error(error);console.error(serviceLog);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await stopService();});
